### ISSUE TITLE
Explain the theme screenshots?

### ISSUE THREAD

**Issue by nasht00** [lysyi3m/osx-terminal-themes#34]
Hi, sorry newbie here but looking at the screenshots in the readme, I have no idea what all the columns are rows are supposed to represent.
 40m? 1;30m ??

Also, do I have to do something for the text colors to work? Double-clicking on a term file, I see it changes the background color and the "main" text color, but everything is the same color, no differences between folders and files, or the prompt, etc. Is that supposed to be like this?

**Comment by npoisonivy** [comment]
I found "Color not showing" under the Closed Issue. It talked about how to.

**Comment by lysyi3m** [comment]
@nasht00 

regarding screenshots - as mentioned in [`preview.rb`](https://github.com/lysyi3m/osx-terminal-themes/blob/master/tools/preview.sh#L3-L8) comments, it's ANSI Escape Sequences. You can read more about them [here](http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html) 

regarding the second part about color formatting - yes, as mentioned above, you need to enable color formatting for your shell first. You can find additional info here https://github.com/lysyi3m/osx-terminal-themes/issues/1#issuecomment-148635036

Since this "problem" is reported by surprisngly many users, I've added pre-requirities section into README with the link to that discussion. 

Best regards,
